### ISSUE TITLE
Example code doesnt work with autocannon

### ISSUE THREAD

**Issue by Igorpollo** [fasthttp/router#11]
Hi!
I'm trying to use [autocannon](https://github.com/mcollina/autocannon) to test the performance.
This is the configuration: 
`autocannon -c 10 -d 30 -m POST -b {"data":"teste"} http://localhost:3001/index`

just changed GET to POST. But I get timeout for all the connections.
This is a bug??

**Comment by savsgio** [comment]
Could you share your code? please

**Comment by savsgio** [comment]
I have been testing autocannon POST requests, and it failed when you add `-b "mybody"` to the command,. If you remove it, it works well.

If you try with wrk, works well when you pass a post body.
`wrk -c 5000 -d 30s -t 4 -s post.lua http://localhost:8080`

post.lua
```lua
-- example HTTP POST script which demonstrates setting the
-- HTTP method, body, and adding a header

wrk.method = "POST"
wrk.body   = "foo=bar&baz=quux"
wrk.headers["Content-Type"] = "application/x-www-form-urlencoded"
```

So, i think it's a autocannon's bug

**Comment by savsgio** [comment]
Result:

```bash
$ wrk -c 5000 -d 30s -t 4 -s post.lua http://localhost:8080
Running 30s test @ http://localhost:8080
  4 threads and 5000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    26.17ms   47.82ms   1.96s    92.88%
    Req/Sec    10.66k    11.63k   75.91k    89.04%
  1268698 requests in 30.08s, 229.89MB read
  Socket errors: connect 0, read 3116, write 1, timeout 179
  Non-2xx or 3xx responses: 1268698
Requests/sec:  42173.96
Transfer/sec:      7.64MB
```

**Comment by Igorpollo** [comment]
Yes... worked with wrk.
Possible a autocannon bug...Thanks!
