### ISSUE TITLE
[ASK] How to pass an Object to handler

### ISSUE THREAD

**Issue by Eskies** [fasthttp/router#13]
Hello, I just new to Go-Lang and want to create some microservice to do some query to a database. How to pass sql.DB object to request handler so there is only one sql.DB connection object?

I've search some discussion before like [https://stackoverflow.com/questions/36754619/usage-of-global-variables-with-http-handlers-in-golang](url) and [https://github.com/buaazp/fasthttprouter/issues/48#issuecomment-474375859](url)
But still clueless about this. Please help

**Comment by Eskies** [comment]
I got it, FYI the handler is on another package
Fasthttp/Router is a very efficient package. Thank you.

`r := router.New()`
`r.GET("/", Index)`
`r.POST("/report-generate", func(ctx *fasthttp.RequestCtx) {`
`otherpackage.ReportGenerator(dbConn, ctx)`
`})`
`log.Fatal(fasthttp.ListenAndServe("127.0.0.1:888", r.Handler))`

**Comment by savsgio** [comment]
Nice! 😄 

You could use your `dbConn` as global variable, because is safe-concurrency, but you could add your own objects with `ctx.SetUserValue("<key>, myObject)` inside the context and get it with `ctx.UserValue("<key>").(<typeOfObject>)`
