### ISSUE TITLE
Readme link to prometheus metrics implementation

### ISSUE THREAD

**Issue by Mnwa** [fasthttp/router#14]
Hey! I forked [flf2ko/fasthttp-prometheus](https://github.com/flf2ko/fasthttp-prometheus) and changed it to your router implementation. Can you add link to you readme for the [Mnwa/fasthttprouter-prometheus](https://github.com/Mnwa/fasthttprouter-prometheus)?

**Comment by savsgio** [comment]
Yes, of course.
Please, make a PR and I will merge it. :smile:

**Comment by Mnwa** [comment]
@savsgio done :D
