### ISSUE TITLE
Issue with trailing slashes

### ISSUE THREAD

**Issue by jonathan-kosgei** [fasthttp/router#16]
The following code does not handle trailing slashes as expected. The docs say that requests with a trailing slash will be handled the same as without a trailing slash. This does not work in the below code;

```
package main

import (
	"fmt"
	"github.com/fasthttp/router"
	"github.com/valyala/fasthttp"
	"log"
	"time"
)

var (
	s = &fasthttp.Server{
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  120 * time.Second,
		GetOnly:      true,
	}
)

func greet(ctx *fasthttp.RequestCtx) {
	ctx.WriteString(fmt.Sprintf("Hi %s\n", ctx.UserValue("name").(string)))
}

func main() {
	r := router.New()
	r.RedirectTrailingSlash = true
	r.GET("/:name", greet)
	s.Handler = r.Handler
	log.Fatal(s.ListenAndServe(":8080"))
}
```
Testing this gives;

```
jonathan@ubuntu:~$ curl 127.0.0.1:8080/joe
Hi joe
jonathan@ubuntu:~$ curl 127.0.0.1:8080/joe/
jonathan@ubuntu:~$
```
If there is a trailing slash the handler is not executed. How would I fix this?

**Comment by kirillDanshin** [comment]
@jonathan-kosgei Hi.

Actually, everything works as expected.

1) if you call curl in verbose mode, you'll see redirect TSR:
```
curl -vvvvv 127.1:8080/joe/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.1 (127.0.0.1) port 8080 (#0)
> GET /joe/ HTTP/1.1
> Host: 127.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: fasthttp
< Date: Tue, 24 Sep 2019 17:27:28 GMT
< Content-Length: 0
< Location: http://127.1:8080/joe
<
* Connection #0 to host 127.1 left intact
```

2) then, if you set -L flag to follow redirects, you'll see that your request is processed correctly:

```
curl -L -vvvvv 127.1:8080/joe/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.1 (127.0.0.1) port 8080 (#0)
> GET /joe/ HTTP/1.1
> Host: 127.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: fasthttp
< Date: Tue, 24 Sep 2019 17:28:13 GMT
< Content-Length: 0
< Location: http://127.1:8080/joe
<
* Connection #0 to host 127.1 left intact
* Issue another request to this URL: 'http://127.1:8080/joe'
* Found bundle for host 127.1: 0x7f89d7008360 [can pipeline]
* Re-using existing connection! (#0) with host 127.1
* Connected to 127.1 (127.0.0.1) port 8080 (#0)
> GET /joe HTTP/1.1
> Host: 127.1:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: fasthttp
< Date: Tue, 24 Sep 2019 17:28:13 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 7
<
Hi joe
* Connection #0 to host 127.1 left intact
```

**Comment by jonathan-kosgei** [comment]
You're right! My bad, thank you for explaining this.

**Comment by jonathan-kosgei** [comment]
Is there a way to handle this without a redirect?

**Comment by savsgio** [comment]
Do you mean to process and send the correct response without redirection?

**Comment by jonathan-kosgei** [comment]
Yes, to match the route without a redirect, I'm building an developer-focused API so a lot of users will try out the service from their command lines and they will not know they need to setup following redirects with curl.

**Comment by savsgio** [comment]
I'm sorry, but these is not the correct functioning, because the registered path is not the requested path. That's why redirection is done only when the difference is the trailing slash.

You could make the following redirect until end, and for the new requests go to the correct path, just like the browsers done (transparent to the user)
