### ISSUE TITLE
Question/Feature Request - Adding a "use" method to Router

### ISSUE THREAD

**Issue by Manghud** [fasthttp/router#19]
Hello. I really like this project. I would like to request to add a method to apply middleware to a whole group/router. I'm willing to contribute if needed

**Comment by savsgio** [comment]
Hi @Manghud,

These feature is easy to implement, wrapping your handler. 

So, some frameworks give you this functionality on easy way like [Atreugo](https://github.com/savsgio/atreugo), [Gramework](https://github.com/gramework/gramework) and others.

But if you want, you could make a PR and we will review it.

Thanks!

**Comment by winduptoy** [comment]
@savsgio I'm not sure this is possible to implement by wrapping the handler if you want to add middleware before the routes but after the router's built-in redirection/`HandleMethodNotAllowed` middleware. For example, if I wrap the handler like this:

```
r := router.New()
r.RedirectTrailingSlash = true
r.RedirectFixedPath = true
r.HandleMethodNotAllowed = true

r.GET("/hello", helloHandler)

fasthttp.ListenAndServe(":8080", func(ctx *fasthttp.RequestContext) {
    // my middleware here
    r.Handler(ctx)
})
```
The order of execution for a request to `/hello` is this:

1. my middleware wrapper function
2. `router`'s `RedirectTrailingSlash`, `RedirectFixedPath`, and `HandleMethodNotAllowed` logic
3. `helloHandler`

What I would like is the ability to run them in this order:

1. `router`'s `RedirectTrailingSlash`, `RedirectFixedPath`, and `HandleMethodNotAllowed` logic
2.  my middleware wrapper function
3. `helloHandler`

If I understand correctly, this is only possible with a `Use` method or something similar, like @Manghud described, right?

**Comment by savsgio** [comment]
Hi @Manghud,

Sorry for delayed answer.

If you want thats behaviour, you must wrap the `helloHandler` and not execute the middleware before the `r.Handler`.

So if you need a simple API to do that you could use some of frameworks built on top of fasthttp.
