### ISSUE TITLE
Method Specific Cache

### ISSUE THREAD

**Issue by kirillDanshin** [fasthttp/router#2]
I'm considering migration from fasthttprouter embedded version to `fasthttp/router` in [Gramework](https://github.com/gramework/gramework). To do that, I need two features:
- method-specific cache. you can see working implementation [here](https://github.com/gramework/gramework/blob/dev/fasthttprouter_cache.go#L1).
- Optional: an option for integration of custom contexts.

**Comment by savsgio** [comment]
I will accept your PR :smile:

**Comment by kirillDanshin** [comment]
in current Go version it's faster to omit such cache, so this is unneded
