### ISSUE TITLE
wildcard segment ':slug' conflicts with existing children in path '/:slug'

### ISSUE THREAD

**Issue by toby3d** [fasthttp/router#20]
Same as buaazp/fasthttprouter#49.

I want use `/` path for render index page and `/:slug` for render specific content by it's `:slug`. I am aware about the hack through `router.NotFound`, but, firstly, this is not most obvious way, and secondly, it requires additional validations for the correct transitions between the necessary pages.

## Example

```go
func main() {
	...
	
	r := router.New()
	handler.RegisterAPI(r.Group("/api")) // api
	handler.RegisterTemplates(r) // renders
}

func (h *MyHandlers) RegisterTemplates(g *router.Router) {
	g.GET("/", h.RenderIndex)
	g.GET("/:slug", h.RenderSlug)
}


func (h *MyHandlers) RegisterAPI(g *router.Router) {
	g.GET("/", h.ShowAll)
	g.GET("/:slug", h.ShowOne)
}
```

**Comment by savsgio** [comment]
Hi @toby3d,

I will try to discover the error and i will fix it.

Thanks for issue.

**Comment by savsgio** [comment]
Hi @toby3d,

Which values could have the `:slug` parameter?

**Comment by toby3d** [comment]
Any alphanum combinations and '-', like: 'hello-world', 'answer42', '300-is-not-200' and so on.

**Comment by savsgio** [comment]
I'm researching about the issue.
When I have something, I will tell here.

**Comment by savsgio** [comment]
I'm working to add support for make the router more flexible, but i will take a few more days.

@toby3d

**Comment by toby3d** [comment]
@savsgio That's ok, take your time. 👍🏻

**Comment by savsgio** [comment]
It's fixed on branch master.

Soon, i will release a new version!
