### ISSUE TITLE
Disallow dot in path

### ISSUE THREAD

**Issue by akaNightmare** [fasthttp/router#24]
Hello, I have a route
`r.GET("/file/:file.json", routes.GetFile)`
and request `GET localhost:8080/file/somefile.json`
I am expecting `ctx.UserValue("file") -> "somefile"`
but received `ctx.UserValue("file.json") -> somefile.json`

How to correctly process this behaviour, without any additional trimming and etc?

**Comment by savsgio** [comment]
Hi @akaNightmare,

The name and value of the param is the full segment in the path, i mean, everything insides between of previous slash before  and the next slash or end of the path.

**Comment by savsgio** [comment]
Hi @akaNightmare,

Don't worry, because I will support regex in paramaters with a new form to declare the parameters in urls

**Comment by akaNightmare** [comment]
@savsgio any news?)

**Comment by savsgio** [comment]
Hi @akaNightmare,

I've been merged it into master.

But I broke the backward compatibility about params because it wasn't enough flexible.

Soon, i will release the version `v1.0.0`

**Comment by savsgio** [comment]
Please see this section and following:

https://github.com/fasthttp/router#named-parameters

**Comment by akaNightmare** [comment]
@savsgio what about atreugo, will that framework support this feature?

**Comment by savsgio** [comment]
@akaNightmare When I release the v1.0.0, I will add it in Atreugo. ;)

**Comment by savsgio** [comment]
@akaNightmare,

It's already available in Atreugo.

**Comment by akaNightmare** [comment]
@savsgio great news! THANKS A LOT.
