### ISSUE TITLE
Need a way to write unit test with url parameters [SOLVED]

### ISSUE THREAD

**Issue by RiskyFeryansyahP** [fasthttp/router#27]
hello, I want to ask about how to do unit testing when I have `url parameters`(e.g /:name) on my url ? 
because at this fasthttp they uses `requestCtx`,  I am a little confused to do unit tests when I have url parameters.

Thanks before,

**Comment by savsgio** [comment]
Hi @RiskyFeryansyahP,

You could do something like this:

```go
func TestParam(t *testing.T) {
	routed := false
	wantParam := "gopher"

	handler := func(ctx *fasthttp.RequestCtx) {
		routed = true
	}

	router := New()
	router.GET("/{name}", handler)

	ctx := new(fasthttp.RequestCtx)
	ctx.Request.SetRequestURI("/" + wantParam)

	router.Handler(ctx)

	if !routed {
		t.Fatal("routing failed")
	}

	param, ok := ctx.UserValue("name").(string)

	if !ok {
		t.Errorf("wrong param value: param value is nil")
	}

	if param != want {
		t.Errorf("wrong param value: want %s, got %s", want, param)
	}
}
```

**Comment by RiskyFeryansyahP** [comment]
Thanks for answer @savsgio ,

Your answer works well, thanks for the explanation, I really appreciate it @savsgio 

i will close this

**Comment by savsgio** [comment]
You are welcome :wink:
