### ISSUE TITLE
request filter

### ISSUE THREAD

**Issue by GuoxinL** [fasthttp/router#28]
Hello, may I ask, how can I implement the filter, before all requests, after the request add the filter, in the outer layer

**Comment by savsgio** [comment]
Hi @GuoxinL,

Do you meaning about middlewares?

**Comment by GuoxinL** [comment]
是的，不知道这个router框架是否支持这个功能；如果不支持的话，根据middlewares关键词在github上搜到了Lu框架，不知道好不好用，能不能和router整合到一起？

**Comment by GuoxinL** [comment]
Yes, I don't know if the "router" framework supports this feature; If not, [Lu](https://github.com/vincentLiuxiang/lu) framework is found on github according to the keyword "middlewares". I wonder if it is good to use. Can it be integrated with "router"?
My English is not very good, please forgive me

**Comment by savsgio** [comment]
Duplicated. Please see: https://github.com/fasthttp/router/issues/19 😉

**Comment by GuoxinL** [comment]
thank you
