### ISSUE TITLE
Not removing superfluous path elements like ////

### ISSUE THREAD

**Issue by kaibox-git** [fasthttp/router#40]
I use code from: https://github.com/fasthttp/router/tree/v1.3.1/_examples/basic
All in default.
Checking "**fix wrong cases and remove superfluous path elements (like ../ or //)**" because my currect web-server doesn't do it.

http://localhost:8080/ works, it is normal
http://localhost:8080///// works too, not expected
http://localhost:8080////hello/////name  works, does not redirect to correct http://localhost:8080/hello/name
But if I use capital letters:
http://localhost:8080////hELLO/////name
it correctly redirects to http://localhost:8080/hello/name removing reduntant slashes.

**Comment by savsgio** [comment]
Hi @kaibox-git,

Well seen, I've just fixed it.

Thanks! :wink:

**Comment by savsgio** [comment]
Take a look to the new release [v1.3.2](https://github.com/fasthttp/router/releases/tag/v1.3.2) 🎉

**Comment by kaibox-git** [comment]
It works, thank you!

**Comment by kaibox-git** [comment]
But 
r.GET("/", Index)
removing the last single slash. Typed and expected http://localhost/, but redirecting to http://localhost.

**Comment by savsgio** [comment]
Hi @kaibox-git,

The trailing slash is removed by the browser, not by the router with a redirection.

You could check it with a curl:

```bash
$ curl http://localhost:8080/ -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: fasthttp
< Date: Sun, 06 Sep 2020 14:57:50 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 9
< 
Welcome!
* Connection #0 to host localhost left intact
* Closing connection 0
```
