### ISSUE TITLE
ServeFilesCustom responds for a long time when requesting a non existent file

### ISSUE THREAD

**Issue by kaibox-git** [fasthttp/router#41]
1. I need to make a route for /assets/. It works quickly if file exists, but if not it takes 2 seconds to response 404 in a folder that contains only 2 files. Why so long (testing on Windows 10)? I'm afraid it is a way for DOS attacks. Same request - again 2 seconds for 404 response.

```
r.ServeFilesCustom("/assets/{filepath:*}", &fasthttp.FS{
		Root:         "./assets",
		PathNotFound: NotFound, // here I can handle and LOG it if needed
		Compress:     true,
	})

```
And the system outputs to console the message: 

```
2020/09/04 10:20:42 5.411 #0000000100000002 - 127.0.0.1:8090<->127.0.0.1:58104 
- GET http://test.local:8080/assets/js/asfgsf - cannot open file "./assets/js/asfgsf": open ./assets/js/asfgsf: The system cannot find the file specified.

```
Is there a way to suppress this message? What's it for in the console? This is only a useless waste of resources.

2. http://test.local:8080/assets/////js////jquery-3.4.1.min.js
 stays with redundant slashes in new release v1.3.2

**Comment by kaibox-git** [comment]
It became clear, 404 - long operation in this case having only 10 routes.

**Comment by kaibox-git** [comment]
Sorry, it because of emailing.

**Comment by savsgio** [comment]
@kaibox-git  Could you fix it?

**Comment by savsgio** [comment]
About the redundant slashes in the `/assets/////js////jquery-3.4.1.min.js` it's due to the `file path` value is not cleaned because it's a variable and not an static path, so it's the expected behaviour.
