### ISSUE TITLE
ServeFilesCustom calls PanicHandler if file does not exist

### ISSUE THREAD

**Issue by kaibox-git** [fasthttp/router#43]
My router for domain http://st.domain.test
```
func StaticRouter(r *router.Router) {
	r.NotFound = NotFound
	r.MethodNotAllowed = MethodNotAllowed
	r.PanicHandler = InternalServerError

	r.ServeFilesCustom("/{filepath:*}", &fasthttp.FS{
		Root:          "./static",
		PathNotFound:  NotFound,
		CacheDuration: time.Hour * 24 * 30,
	})
}
```
For not existing request, for example, http://st.domain.test:8090/abrakadabra, router write to console:
2020/12/17 10:11:07 0.960 #0000000800000003 - 127.0.0.1:8090<->127.0.0.1:50255 - GET http://st.domain.test:8090/abrakadabra - cannot open file "./static/abrakadabra": open ./static/abrakadabra: The system cannot find the file specified.
And calls handler for PanicHandler. I expect "NotFound" in this situation.

**Comment by erikdubbelboer** [comment]
Can you share your `NotFound` function? Are you sure there isn't a panic happening in here?

**Comment by kaibox-git** [comment]
Yes, you are right. Sorry.
