### ISSUE TITLE
Get Matched Route

### ISSUE THREAD

**Issue by matheus-meneses** [fasthttp/router#48]
How can i get the matched route in my handle?

Example: 

Assuming that i've registered the route 

r.GET("/hello/{name}", Hello)

In Hello handle i would like to get "/hello/{name}" path

Is it possible?

**Comment by savsgio** [comment]
Hi @matheus-meneses,

You could get the matched route:

```go
r := router.New()
r.SaveMatchedRoutePath = true

func myHandler(ctx *fasthttp.RequestCtx) {
     matchedRoute := ctx.UserValue(router.MatchedRoutePathParam).(string)
     fmt.Println("Route:", matchedRoute)
}
```
