### ISSUE TITLE
What's the difference with  buaazp/fasthttprouter?

### ISSUE THREAD

**Issue by iamybj** [fasthttp/router#5]
What's the difference with  buaazp/fasthttprouter?
And why not add middleware feature?

**Comment by savsgio** [comment]
It's the same repository, but [fasthttp/router](https://github.com/fasthttp/router) is maintained by the fasthttp-team and has some fixes and enhancements in performance with respect to [buaazp/fasthttprouter](https://github.com/buaazp/fasthttprouter)

Anyway, @buaazp has permissions to make changes here as author.

**Comment by jamiesonbecker** [comment]
Hmm, it seems that it is _not_ the same repository.

If the fasthttp repo has fixes with respect to the original @buaazp (who bears thanks for porting this from net/http in the first place), then it's effectively a fork. One of these repos should be put in archive mode.

Even though you are both working together (the fasthttp team and @buaazp), you are maintaining two different trunks for no apparent reason.

Right now, this results in confusion to potential users and, potentially, security vulnerabilities where a patch is applied to one and not the other. At best, it's double work for everyone -- maintainers, pull requesters, and users. At worst, some fixes will be made to one and not the other.

Please just choose one repo that will be master/HEAD moving forward and archive the other with a link to the one that's the new main repo. It doesn't really matter which one it is, except for marketing purposes.

**Comment by savsgio** [comment]
@jamiesonbecker Oh sorry, I meant `fork`.

I would like buaazp will be archive her repository, but @buaazp never answer, only accepted our invitation to add him to the router, but no more.

Anyway, I recommend you to use fasthttp router because I think the buuazp/fasthttprouter now is broken.

**Comment by kirillDanshin** [comment]
@buaazp don't have permissions, he didn't accept the invitation yet

![image](https://user-images.githubusercontent.com/9026581/57330319-51645c00-711e-11e9-9659-3b71d87e161f.png)
