### ISSUE TITLE
Why this routing doesn't work?

### ISSUE THREAD

**Issue by josegoval** [fasthttp/router#50]
```
router.GET("/hello", helloHandlerFunc)
router.GET("/{param}", paramHandler)
```

When I try to get `/hellowhatever`, or even any that start with "h" like `/hey`, it returns `ERR_TOO_MANY_REDIRECTS`.

Why is this happening?

**Comment by savsgio** [comment]
Hi @josegoval,

I've tried it and it works fine!.

Could you share more information, like a `curl` log, please?

**Comment by josegoval** [comment]
@savsgio Yea sure, this is my code. I was debugging, and I found out 
`package main

import (
	"encoding/json"
	"fmt"

	"github.com/fasthttp/router"
	"github.com/valyala/fasthttp"
)

type SimpleStruct struct {
	Name   string   `json:"name"`
	Number int      `json:"number"`
	None   []string `json:"none,omitempty"`
}

func main() {

	router := router.New()

	// Setting up routes
	router.GET("/hello", helloHandlerFunc)
	router.GET("/has-cookie", hasCookieHandlerFunc)
	router.GET("/{param}", paramHandler)

	fasthttp.ListenAndServe(":8080", router.Handler)

}

func paramHandler(ctx *fasthttp.RequestCtx) {
	param := ctx.UserValue("param")

	ctx.SetBodyString(param.(string))
}

func helloHandlerFunc(ctx *fasthttp.RequestCtx) {
	simple := SimpleStruct{Name: "Jose", Number: 7}
	bytes, err := json.Marshal(simple)
	if err != nil {
		ctx.Error(err.Error(), fasthttp.StatusInternalServerError)
		return
	}

	ctx.SetContentType("application/json")
	ctx.SetStatusCode(fasthttp.StatusOK)
	ctx.SetBody(bytes)
}

func hasCookieHandlerFunc(ctx *fasthttp.RequestCtx) {
	cookie := ctx.Request.Header.Cookie("auth-token")
	fmt.Println(string(cookie), cookie)

	if cookie == nil {
		ctx.Error("You dont have the cookie!", fasthttp.StatusUnauthorized)
		return
	}

	ctx.SetContentType("application/json")
	ctx.SetStatusCode(fasthttp.StatusOK)
	ctx.SetBodyString(string(cookie))
}
`

And when I try to go to for example: `localhost:8080/hello1` I get a lot of redirections like this one:
```
Request URL: http://localhost:8080/hello1
Request Method: GET
Status Code: 301 Moved Permanently
Remote Address: 127.0.0.1:8080
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by savsgio** [comment]
Hi @josegoval,

I found the bug, so i could try to fix it soon. 

Thanks for the issue!

**Comment by savsgio** [comment]
@josegoval Fixed it! 😉
