### ISSUE TITLE
How to integrate with Prometheus

### ISSUE THREAD

**Issue by 352174109** [fasthttp/router#53]
I want to export my metric with prometheus. But how I add the handler

**Comment by savsgio** [comment]
Hi @352174109,

You must convert the [prometheus http handler](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/http.go#L74) to a fasthttp request handler with [fasthttpadaptor](https://github.com/valyala/fasthttp/tree/master/fasthttpadaptor):

```go
r := router.New()

prometheusRequestHandler := fasthttpadaptor.NewFastHTTPHandler(promhttp.Handler())
r.GET("/<your path>", prometheusRequestHandler)
```
