### ISSUE TITLE
gotils is gpl

### ISSUE THREAD

**Issue by csrl** [fasthttp/router#58]
Hello, this repo use github.com/savsgio/gotils which is gpl3. Can you look at replacing with a compatible license for fasthttp/router? Thanks.

**Comment by yangjuncode** [comment]
you may be wrong, it's Apache License 2.0. https://github.com/savsgio/gotils/blob/master/LICENSE

**Comment by csrl** [comment]
You are right, thank you.  We were using an older version of fasthttp router that was still using the gotils GPL licensed version. Current releases are not affected.
