### ISSUE TITLE
panic: path must begin with '/' in path ''  group.go:19

### ISSUE THREAD

**Issue by TankTim68** [fasthttp/router#66]
user := sm.Group("/user ")
	user .GET("", h.UserHomePage)
	
	error:
	panic: path must begin with '/' in path ''

group.go

`func (g *Group) GET(path string, handler fasthttp.RequestHandler) {
	validatePath(path)

	g.router.GET(g.prefix+path, handler)
}`

**Should it be changed to**

`func (g *Group) GET(path string, handler fasthttp.RequestHandler) {
	validatePath(g.prefix+path)

	g.router.GET(g.prefix+path, handler)
}`

**Comment by savsgio** [comment]
Hi @TankTim68,

Issue duplicated: https://github.com/fasthttp/router/issues/65
